#!/bin/bash 

set -e

# Install homebrew
which -s brew 
echo Installing Brew...
if [ $? -eq 0 ]; then 
  echo "  skipping. Already installed!"
else
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install fonts
brew tap homebrew/cask-fonts &&
brew install \
  font-fira-code-nerd-font \
  font-iosevka-nerd-font \
  font-victor-mono-nerd-font 


# Install casks with homebrew
brew install --cask \
	amethyst \
	dash \
	discord \
	docker \
	google-cloud-sdk \
	google-drive \
	kitty \
	obsidian \
	orbstack \
	postman \
	zoom 

# Skipped
	# dbeaver-community \
	# pgadmin4 \

# Install utilities
brew install \
  asdf \
  docker \
  git \
  helm \
  kind \
  kubectx \
  lazygit \
  neovim \
  postgresql@14 \
  powerlevel10k \
  ripgrep \
  sqllite \
  tilt \
  tmux \
  tree-sitter 


